name: CI
on: push

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.2
      - name: Build
        run: docker build -t pwagner/awscli .
      - name: Test
        run: docker run --rm pwagner/awscli aws --version
      